### PR TITLE
Added Hungarian Translation again

### PR DESCRIPTION
**Pull request by attilam**
Here's a second try. Please disregard the other other one :)

### CODE REVIEW

**Comment by neauoire** [comment]
Perfect!! Implementing now, let's see what this looks like ^__^

**Comment by attilam** [comment]
I used the en, ger, jp as references; I think it turned out quite alright, "Hungarian sounding"!

I also added myself to the hun credits.

**Comment by neauoire** [comment]
My god hungarian is beautiful.

**Comment by attilam** [comment]
Haha, it's a monster of a language, with long words and accented characters all over the place :D

**Comment by neauoire** [comment]
There are a few things that I can't render properly.
like &ouml; and &#337; and a few others.
I've converted some of the a and e and o, into a format that will draw well.

Could you put these characters in UTF8 format into lang.hu?

**Comment by attilam** [comment]
Alright, let me check it out. ő is especially bothersome as many fonts don't even have it. Told you, it's a monster! :)

**Pull request merged**
